language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
  - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-* && ./configure && make && sudo make install && popd
  - wget -q https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.2.tar.gz
  - tar xzf SDL2_image-*.tar.gz
  - pushd SDL2_image-* && ./configure && make && sudo make install && popd
install:
  - sudo apt-get install cmake cmake-data
script: 
  - mkdir build
  - cd build
  - cmake ../ && make
