language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:george-edison55/precise-backports
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get -qq update
install:
  - sudo apt-get install libsdl2-dev libsdl2-image-dev cmake cmake-data
script: 
  - mkdir build
  - cd build
  - cmake ../ && make
